services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: smart-tasks-app
        container_name: smart-tasks-app
        restart: unless-stopped
        ports:
            - "8000:8000"
        environment:
            APP_ENV: local
            APP_DEBUG: true
            APP_KEY: base64:GENERATE_IT
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: secret
            REDIS_HOST: redis
            REDIS_PASSWORD: null
            REDIS_PORT: 6379
        depends_on:
            - db
            - redis
        volumes:
            - .:/var/www/html

    db:
        image: mysql:8.0
        container_name: smart-tasks-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    redis:
        image: redis:7
        container_name: smart-tasks-redis
        restart: unless-stopped
        ports:
            - "6379:6379"

volumes:
    db_data:
