name: 🚀 Deploy Smart-Tasks API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🎉 Deploy to Server
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: 🚚 Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup PHP
      - name: 🚀 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: mbstring, bcmath, curl, xml, json
          ini-values: post_max_size=256M, upload_max_filesize=256M

      # 3️⃣ FTP Deploy files
      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/.env
            **/composer.lock
            **/package-lock.json
            **/.htaccess
            **/storage/**

      # 4️⃣ SSH to server and run post-deploy commands
      - name: ⚡ Run commands on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /path/to/your/project
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan queue:restart
            php artisan l5-swagger:generate
